
stages:
  - containers
  - builds
  - sanity_checks

.native_build_job:
  script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
    - $MAKE

.native_build_job_prebuilt_env:
  extends:
    - .native_build_job
    - .gitlab_native_build_job_prebuilt_env

.native_build_job_local_env:
  extends:
    - .native_build_job
    - .gitlab_native_build_job_local_env

include: '/ci/gitlab.yml'
