
stages:
  - prebuild
  - containers
  - docs

.container_job_template: &container_job_definition
  image: docker:stable
  stage: containers
  services:
    - name: registry.gitlab.com/libvirt/libvirt-ci/docker-dind:master
      alias: docker
  before_script:
    - export TAG="$CI_REGISTRY_IMAGE/ci-$NAME:latest"
    - export COMMON_TAG="$CI_REGISTRY/libvirt/libvirt-publican/ci-$NAME:latest"
    - docker info
    - docker login registry.gitlab.com -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker pull "$TAG" || docker pull "$COMMON_TAG" || true
    - docker build --cache-from "$TAG" --cache-from "$COMMON_TAG" --tag "$TAG" -f "ci/containers/ci-$NAME.Dockerfile" ci
    - docker push "$TAG"
  after_script:
    - docker logout

.docs_job_template: &docs_job_definition
  image: $CI_REGISTRY_IMAGE/ci-$NAME:latest
  stage: docs
  before_script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
  script:
    - $MAKE

# Check that all commits are signed-off for the DCO.
# Skip on "libvirt" namespace, since we only need to run
# this test on developer's personal forks from which
# merge requests are submitted
check-dco:
  stage: prebuild
  image: registry.gitlab.com/libvirt/libvirt-ci/check-dco:master
  script:
    - /check-dco
  except:
    variables:
      - $CI_PROJECT_NAMESPACE == 'libvirt'


debian-10-container:
  <<: *container_job_definition
  variables:
    NAME: debian-10

debian-sid-container:
  <<: *container_job_definition
  variables:
    NAME: debian-sid

fedora-32-container:
  <<: *container_job_definition
  variables:
    NAME: fedora-32

fedora-33-container:
  <<: *container_job_definition
  variables:
    NAME: fedora-33

fedora-rawhide-container:
  <<: *container_job_definition
  variables:
    NAME: fedora-rawhide

ubuntu-1804-container:
  <<: *container_job_definition
  variables:
    NAME: ubuntu-1804

ubuntu-2004-container:
  <<: *container_job_definition
  variables:
    NAME: ubuntu-2004


debian-10-docs:
  <<: *docs_job_definition
  variables:
    NAME: debian-10

debian-sid-docs:
  <<: *docs_job_definition
  variables:
    NAME: debian-sid

fedora-32-docs:
  <<: *docs_job_definition
  variables:
    NAME: fedora-32

fedora-33-docs:
  <<: *docs_job_definition
  variables:
    NAME: fedora-33

fedora-rawhide-docs:
  <<: *docs_job_definition
  variables:
    NAME: fedora-rawhide

ubuntu-1804-docs:
  <<: *docs_job_definition
  variables:
    NAME: ubuntu-1804

ubuntu-2004-docs:
  <<: *docs_job_definition
  variables:
    NAME: ubuntu-2004
