
stages:
  - containers
  - builds
  - sanity_checks

.native_build_job:
  extends: .gitlab_native_build_job
  before_script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
  script:
    - $MAKE

include: '/ci/gitlab.yml'
